### ISSUE TITLE
Bug Last Versions

### ISSUE THREAD

**Issue by DarsoX** [mrwan200/EnkaNetwork.py#15]
========== RESTART: C:\Users\DarsoX\Desktop\STAT\statistick\newMain.py =========
Traceback (most recent call last):
  File "C:\Users\DarsoX\Desktop\STAT\statistick\newMain.py", line 4, in <module>
    from enkanetwork import EnkaNetworkAPI,Assets
  File "C:\Users\DarsoX\AppData\Local\Programs\Python\Python39\lib\site-packages\enkanetwork\__init__.py", line 8, in <module>
    from .client import *
  File "C:\Users\DarsoX\AppData\Local\Programs\Python\Python39\lib\site-packages\enkanetwork\client.py", line 12, in <module>
    from .cache import Cache
  File "C:\Users\DarsoX\AppData\Local\Programs\Python\Python39\lib\site-packages\enkanetwork\cache.py", line 4, in <module>
    from cachetools import TTLCache
ModuleNotFoundError: No module named 'cachetools'

Traceback (most recent call last):
  File "C:\Users\DarsoX\Desktop\STAT\statistick\newMain.py", line 380, in <module>
    main(724281429)
  File "C:\Users\DarsoX\Desktop\STAT\statistick\newMain.py", line 372, in main
    img = bgStart(r.characters[0].id)
  File "C:\Users\DarsoX\Desktop\STAT\statistick\newMain.py", line 184, in bgStart
    banner = imagePase(person.images.banner, size = (2095,1048), thum = True)
  File "C:\Users\DarsoX\Desktop\STAT\statistick\newMain.py", line 142, in imagePase
    imgs = Image.open(BytesIO(requests.get(link).content))
  File "C:\Users\DarsoX\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\DarsoX\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\DarsoX\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\DarsoX\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 695, in send
    adapter = self.get_adapter(url=request.url)
  File "C:\Users\DarsoX\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 792, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for "filename='UI_Gacha_AvatarImg_Shougun' url='https://enka.network/ui/UI_Gacha_AvatarImg_Shougun.png'"

**Comment by mrwan200** [comment]
You must be install `cachetools` like this:
```
pip install cachetools
```

And you must get url in `IconAsset` class like this:

https://github.com/mrwan200/EnkaNetwork.py/blob/e90033168fcf11ca41abea4da02659e58fc0fdbe/example/characters.py#L21

Or you can see in https://github.com/mrwan200/EnkaNetwork.py#icon-data

**Comment by DarsoX** [comment]
> You must be install `cachetools` like this:
> 
> ```
> pip install cachetools
> ```
> 
> And you must get url in `IconAsset` class like this:
> 
> https://github.com/mrwan200/EnkaNetwork.py/blob/e90033168fcf11ca41abea4da02659e58fc0fdbe/example/characters.py#L21
> 
> Or you can see in https://github.com/mrwan200/EnkaNetwork.py#icon-data

There was no second error in the previous version, is this an update?

**Comment by mrwan200** [comment]
> > You must be install `cachetools` like this:
> > ```
> > pip install cachetools
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And you must get url in `IconAsset` class like this:
> > https://github.com/mrwan200/EnkaNetwork.py/blob/e90033168fcf11ca41abea4da02659e58fc0fdbe/example/characters.py#L21
> > 
> > Or you can see in https://github.com/mrwan200/EnkaNetwork.py#icon-data
> 
> There was no second error in the previous version, is this an update?

Yup It's new update
