### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by DEViantUA** [mrwan200/EnkaNetwork.py#21]
```
import asyncio
from enkanetwork import EnkaNetworkAPI

async def info(uid = None,lang = "en"):
    async with EnkaNetworkAPI(lang=lang) as client:
        r = await client.fetch_user(uid)
    return r
for key in [uid1, uid2]:
  r = asyncio.run(info(uid = key))
```

ERROR:

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022531803130>
Traceback (most recent call last):
  File "C:\Users\userName\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\userName\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\userName\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\userName\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

How to fix this error? I don't write in ansynchronous, so all I need from it is just a call to this function.

**Comment by DEViantUA** [comment]
I found a solution to the problem, if someone encounters, then the following fixed this problem:

after import asyncio you need to write: asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())


This error is caused by Windows
