### ISSUE TITLE
EnkaNetwork.py appears to be corrupted

### ISSUE THREAD

**Issue by ZoruaFox** [mrwan200/EnkaNetwork.py#56]
### [Code](https://github.com/TopRealm/akari-bot/blob/genshin/modules/genshin/__init__.py)
```python
async def _(msg: Bot.MessageSession):
    data = await client.fetch_user(msg.parsed_msg['<number>'])
    player_level = {data.player.level}
    await msg.send_message(
        f"玩家昵称：{data.player.nickname}\n"
        f"玩家签名: {data.player.signature}\n"
        f"玩家等级：{data.player.level}\n"
        f"深境螺旋: {data.player.abyss_floor} 层 {data.player.abyss_room} 间\n"
        f"下次查询剩余：{data.ttl} s"
        )
```
### Response
```python
[Aiocqhttp][core.parser.message:parser:359][2024-01-18 10:16:33][ERROR]:Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\akari-bot-dev\akari-bot\core\parser\message.py", line 316, in parser
    await execute_submodule(msg, command_first_word, command_split)
  File "C:\Users\Administrator\Desktop\akari-bot-dev\akari-bot\core\parser\message.py", line 290, in execute_submodule
    await parsed_msg[0].function(**kwargs)  # 将msg传入下游模块
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\akari-bot-dev\akari-bot\modules\genshin\__init__.py", line 18, in _
    data = await client.fetch_user(msg.parsed_msg['<number>'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\akari-bot-3uC3wRUU-py3.11\Lib\site-packages\enkanetwork\client.py", line 205, in fetch_user_by_uid
    return EnkaNetworkResponse.parse_obj(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\akari-bot-3uC3wRUU-py3.11\Lib\site-packages\typing_extensions.py", line 2499, in wrapper
    return arg(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\akari-bot-3uC3wRUU-py3.11\Lib\site-packages\pydantic\main.py", line 1027, in parse_obj
    return cls.model_validate(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\akari-bot-3uC3wRUU-py3.11\Lib\site-packages\pydantic\main.py", line 503, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 49 validation errors for EnkaNetworkResponse
playerInfo.profilePicture.nameTextMapHash
  Input should be a valid string [type=string_type, input_value=1533656818, input_type=int]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
playerInfo.showAvatarInfoList.0.avatarId
  Input should be a valid string [type=string_type, input_value=10000052, input_type=int]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
playerInfo.showAvatarInfoList.1.avatarId
  Input should be a valid string [type=string_type, input_value=10000056, input_type=int]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
playerInfo.showAvatarInfoList.2.avatarId
  Input should be a valid string [type=string_type, input_value=10000047, input_type=int]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
playerInfo.showAvatarInfoList.3.avatarId
  Input should be a valid string [type=string_type, input_value=10000032, input_type=int]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
playerInfo.showAvatarInfoList.4.avatarId
  Input should be a valid string [type=string_type, input_value=10000030, input_type=int]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
playerInfo.showAvatarInfoList.5.avatarId
  Input should be a valid string [type=string_type, input_value=10000037, input_type=int]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
playerInfo.showAvatarInfoList.6.avatarId
  Input should be a valid string [type=string_type, input_value=10000075, input_type=int]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
playerInfo.showAvatarInfoList.7.avatarId
  Input should be a valid string [type=string_type, input_value=10000087, input_type=int]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
avatarInfoList.0.equipList.0.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=7.8, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.0.equipList.1.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=5.2, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.0.equipList.2.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=3.9, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.0.equipList.3.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=5.2, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.0.equipList.4.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=6.2, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.1.equipList.0.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=3.5, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.1.equipList.1.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=5.2, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.1.equipList.2.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=5.4, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.1.equipList.3.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=3.1, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.1.equipList.4.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=5.4, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.2.equipList.0.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=7.3, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.2.equipList.1.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=3.5, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.2.equipList.2.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=3.9, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.2.equipList.3.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=2.7, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.2.equipList.4.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=5.2, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.3.equipList.0.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=5.4, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.3.equipList.1.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=6.2, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.3.equipList.2.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=3.9, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.3.equipList.3.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=5.4, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.3.equipList.4.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=3.5, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.4.equipList.0.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=5.2, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.4.equipList.1.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=4.1, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.4.equipList.2.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=2.7, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.4.equipList.3.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=5.4, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.4.equipList.4.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=7.8, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.5.equipList.0.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=4.5, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.5.equipList.1.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=4.7, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.5.equipList.2.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=5.4, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.5.equipList.3.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=7.8, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.5.equipList.4.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=5.8, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.6.equipList.0.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=4.7, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.6.equipList.1.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=6.2, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.6.equipList.2.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=7.8, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.6.equipList.3.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=5.8, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.6.equipList.4.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=5.8, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.7.equipList.0.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=5.8, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.7.equipList.1.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=7.8, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.7.equipList.2.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=4.5, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.7.equipList.3.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=3.1, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
avatarInfoList.7.equipList.4.propValue
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=3.1, input_type=float]
    For further information visit https://errors.pydantic.dev/2.5/v/int_from_float
```

**Comment by Azen0n** [comment]
Downgrade Pydantic to 1.10

**Comment by ZoruaFox** [comment]
> Downgrade Pydantic to 1.10

Thanks for help, problem solved
