### ISSUE TITLE
KeyError: 'avatarId'

### ISSUE THREAD

**Issue by seriaati** [mrwan200/EnkaNetwork.py#7]
```py
Traceback (most recent call last):
  File "C:\Users\seria\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\app_commands\commands.py", line 649, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "C:\Users\seria\shenhe_bot\cogs\genshin.py", line 846, in profile
    data: EnkaNetworkResponse = await enka_client.fetch_user(uid)
  File "C:\Users\seria\AppData\Local\Programs\Python\Python310\lib\site-packages\enkanetwork\client.py", line 65, in fetch_user
    return EnkaNetworkResponse.parse_obj(data)
  File "pydantic\main.py", line 521, in pydantic.main.BaseModel.parse_obj
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1038, in pydantic.main.validate_model
  File "pydantic\fields.py", line 857, in pydantic.fields.ModelField.validate
  File "pydantic\fields.py", line 1074, in pydantic.fields.ModelField._validate_singleton
  File "pydantic\fields.py", line 1121, in pydantic.fields.ModelField._apply_validators
  File "pydantic\class_validators.py", line 313, in pydantic.class_validators._generic_validator_basic.lambda12
  File "pydantic\main.py", line 686, in pydantic.main.BaseModel.validate
  File "C:\Users\seria\AppData\Local\Programs\Python\Python310\lib\site-packages\enkanetwork\model\players.py", line 119, in __init__
    super().__init__(**data)
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1038, in pydantic.main.validate_model
  File "pydantic\fields.py", line 857, in pydantic.fields.ModelField.validate
  File "pydantic\fields.py", line 1074, in pydantic.fields.ModelField._validate_singleton
  File "pydantic\fields.py", line 1121, in pydantic.fields.ModelField._apply_validators
  File "pydantic\class_validators.py", line 313, in pydantic.class_validators._generic_validator_basic.lambda12
  File "pydantic\main.py", line 686, in pydantic.main.BaseModel.validate
  File "C:\Users\seria\AppData\Local\Programs\Python\Python310\lib\site-packages\enkanetwork\model\players.py", line 26, in __init__
    icon = Assets.character_icon(str(data["avatarId"]))
KeyError: 'avatarId'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\seria\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\app_commands\tree.py", line 1157, in call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\seria\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\app_commands\commands.py", line 675, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\seria\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\app_commands\commands.py", line 668, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'profile角色展示' raised an exception: KeyError: 'avatarId'
```

**Comment by mrwan200** [comment]
Fixed https://github.com/mrwan200/EnkaNetwork.py/commit/a36ca4ad5f62943dd01786c94f5a6a200d437259

Please reinstall in this command `pip install git+https://github.com/mrwan200/EnkaNetwork.py`
